[package]
name = "draguation_work"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
tcod = "0.15.0"
winit = "0.26.1"